#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Mvc.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Elfar;
    using Elfar.Mvc;
    using Elfar.Mvc.Properties;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Dashboard.cshtml")]
    public partial class Dashboard : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Dashboard()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<div id=""dashboard"">
    <p>
        Trends:
        <ul>
            <li>90 days</li>
            <li>30 days</li>
            <li>7 days</li>
            <li>today</li>
        </ul>
        <div id=""timeline"" style=""min-width: 310px; height: 150px; margin: 0 auto""></div>
    </p>
    <p>
        Donut charts:
        <ul>
            <li>Areas</li>
            <li>Controllers (per Area)</li>
            <li>Actions (per Controller & Area)</li>
        </ul>
    </p>
    <p>
        List:
        <ul>
            <li>last 10 errors</li>
            <li>10 most common errors</li>
        </ul>
    </p>
</div>");


        }
    }
}
#pragma warning restore 1591
