#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Mvc.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Elfar;
    using Elfar.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Default.cshtml")]
    public partial class Default : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Default()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Error Logging Filter and Rout" +
"e (ELFAR)</title>\r\n        <link href=\"");


            
            #line 5 "..\..\Views\ErrorLog\Default.cshtml"
               Write(Url.Content("~/Styles/StyleSheet.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n    </head>\r\n    <body>\r\n        <header>\r" +
"\n            <div id=\"elfar\">Error Logging Filter and Route (ELFAR)</div>\r\n     " +
"       <div id=\"title\">Dashboard for <strong>");


            
            #line 10 "..\..\Views\ErrorLog\Default.cshtml"
                                             Write(HttpRuntime.AppDomainAppId);

            
            #line default
            #line hidden
WriteLiteral("</strong> on <strong>");


            
            #line 10 "..\..\Views\ErrorLog\Default.cshtml"
                                                                                             Write(Server.MachineName);

            
            #line default
            #line hidden
WriteLiteral("</strong></div>\r\n        </header>\r\n        <div id=\"content\">\r\n            <pre " +
"id=\"stack-trace\">\r\n            </pre>\r\n        </div>\r\n        <footer>Beyond395" +
" Limited &copy; 2011&ndash;");


            
            #line 16 "..\..\Views\ErrorLog\Default.cshtml"
                                               Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" &nbsp; All rights reserved. &nbsp; ");


            
            #line 16 "..\..\Views\ErrorLog\Default.cshtml"
                                                                                                     Write(ErrorLogProvider.Details);

            
            #line default
            #line hidden
WriteLiteral("</footer>\r\n        <script src=\"");


            
            #line 17 "..\..\Views\ErrorLog\Default.cshtml"
                Write(Url.Content("~/Scripts/jquery-2.0.3.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n        <script type=\"text/javascript\">\r\n    " +
"        $(function() {\r\n                $.ajax({ url: \"");


            
            #line 20 "..\..\Views\ErrorLog\Default.cshtml"
                          Write(Url.Content("~/elfar/Errors"));

            
            #line default
            #line hidden
WriteLiteral("\" }).done(function(json) {\r\n                    //$(\"pre#stack-trace\").html(json[" +
"0].StackTrace);\r\n                });\r\n            });\r\n        </script>\r\n    </" +
"body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
