#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Mvc.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Elfar;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Digest.cshtml")]
    public class Digest : System.Web.Mvc.WebViewPage<Elfar.Mvc.Models.Index>
    {
        public Digest()
        {
        }
        public override void Execute()
        {

WriteLiteral("<rss xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www." +
"w3.org/2001/XMLSchema\" version=\"0.91\">\r\n  <channel>\r\n    <title>");


            
            #line 4 "..\..\Views\ErrorLog\Digest.cshtml"
      Write(string.Format("Daily digest of errors for {0} on {1}", Model.Application, Server.MachineName));

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link>");


            
            #line 5 "..\..\Views\ErrorLog\Digest.cshtml"
      Write(Request.Url.GetLeftPart(UriPartial.Authority) + Request.ServerVariables["URL"]);

            
            #line default
            #line hidden
WriteLiteral("</link>\r\n    <description>Daily digest of application errors</description>\r\n    <" +
"language>en</language>\r\n");


            
            #line 8 "..\..\Views\ErrorLog\Digest.cshtml"
 foreach (var group in Model.Errors.GroupBy(e => e.Time.Date))
{
    var date = group.Key;

            
            #line default
            #line hidden
WriteLiteral("    <item>\r\n        <title>Digest for ");


            
            #line 12 "..\..\Views\ErrorLog\Digest.cshtml"
                     Write(date.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 12 "..\..\Views\ErrorLog\Digest.cshtml"
                                                   Write(date.ToLongDateString());

            
            #line default
            #line hidden
WriteLiteral(")</title>\r\n        <description>&lt;ul&gt;\r\n");


            
            #line 14 "..\..\Views\ErrorLog\Digest.cshtml"
         foreach (var errorLog in group) {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("    &lt;li&gt;&lt;span title=\"");


            
            #line 15 "..\..\Views\ErrorLog\Digest.cshtml"
                                   Write(errorLog.Type);

            
            #line default
            #line hidden
WriteLiteral("\"&gt;");


            
            #line 15 "..\..\Views\ErrorLog\Digest.cshtml"
                                                      Write(errorLog.Type.ShortName());

            
            #line default
            #line hidden
WriteLiteral("&lt;/span&gt;: ");


            
            #line 15 "..\..\Views\ErrorLog\Digest.cshtml"
                                                                                               Write(Html.Encode(Html.ActionLink(errorLog.Message, "Default", new { id = errorLog.ID })));

            
            #line default
            #line hidden
WriteLiteral(" &lt;/li&gt;\r\n");


            
            #line 16 "..\..\Views\ErrorLog\Digest.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("            &lt;/ul&gt;</description>\r\n        <pubDate>");


            
            #line 18 "..\..\Views\ErrorLog\Digest.cshtml"
            Write(date.ToString("r"));

            
            #line default
            #line hidden
WriteLiteral("</pubDate>\r\n    </item>\r\n");


            
            #line 20 "..\..\Views\ErrorLog\Digest.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("  </channel>\r\n</rss>");


        }
    }
}
#pragma warning restore 1591
