#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Mvc.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Elfar;
    using Elfar.Mvc;
    using Elfar.Mvc.Properties;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Header.cshtml")]
    public partial class Header : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Header()
        {
        }
        public override void Execute()
        {
WriteLiteral("<header>\r\n    ");


            
            #line 2 "..\..\Views\ErrorLog\Header.cshtml"
Write(Html.Partial("Title"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <ul id=\"tabs\">\r\n        <li class=\"selected\">Dashboard</li>\r\n    </ul>\r\n</h" +
"eader>");


        }
    }
}
#pragma warning restore 1591
