#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Mvc.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Elfar;
    using Elfar.Mvc;
    using Elfar.Mvc.Properties;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Header.cshtml")]
    public partial class Header : System.Web.Mvc.WebViewPage<dynamic>
    {

public System.Web.WebPages.HelperResult Strong(string text, string title) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



WriteLiteralTo(@__razor_helper_writer, " <strong title=\"");



#line 7 "..\..\Views\ErrorLog\Header.cshtml"
                            WriteTo(@__razor_helper_writer, title);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 7 "..\..\Views\ErrorLog\Header.cshtml"
                                    WriteTo(@__razor_helper_writer, text);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</strong> ");



#line 7 "..\..\Views\ErrorLog\Header.cshtml"
                                                                                  
#line default
#line hidden

});

                                                                                  }


        public Header()
        {
        }
        public override void Execute()
        {
WriteLiteral("<header>\r\n    <div>Error Logging Filter and Route / ");


            
            #line 2 "..\..\Views\ErrorLog\Header.cshtml"
                                     Write(Strong(ErrorLogProvider.Application, "The name or id of the web application"));

            
            #line default
            #line hidden
WriteLiteral(" / ");


            
            #line 2 "..\..\Views\ErrorLog\Header.cshtml"
                                                                                                                      Write(Strong(@Server.MachineName, "The name of the server"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n    <ul id=\"tabs\">\r\n        <li class=\"selected\">Dashboard</li>\r\n    </ul" +
">\r\n</header>\r\n");




        }
    }
}
#pragma warning restore 1591
