#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Mvc.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Rss.cshtml")]
    public class Rss : System.Web.Mvc.WebViewPage<Elfar.Mvc.Models.Index>
    {
        public Rss()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\ErrorLog\Rss.cshtml"
   var url = Request.Url; 

            
            #line default
            #line hidden
WriteLiteral("<rss xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www." +
"w3.org/2001/XMLSchema\" version=\"0.91\">\r\n  <channel>\r\n    <title>");


            
            #line 5 "..\..\Views\ErrorLog\Rss.cshtml"
      Write(string.Format("Error log for {0} on {1}", Model.Application, Server.MachineName));

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link>");


            
            #line 6 "..\..\Views\ErrorLog\Rss.cshtml"
      Write(Request.Url.GetLeftPart(UriPartial.Authority) + Request.ServerVariables["URL"]);

            
            #line default
            #line hidden
WriteLiteral("</link>\r\n    <description>Log of recent errors</description>\r\n    <language>en</l" +
"anguage>\r\n");


            
            #line 9 "..\..\Views\ErrorLog\Rss.cshtml"
 foreach (var errorLog in Model.Errors)
{

            
            #line default
            #line hidden
WriteLiteral("    <item>\r\n      <title>");


            
            #line 12 "..\..\Views\ErrorLog\Rss.cshtml"
        Write(errorLog.Message);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n      <description>An errorLog of type ");


            
            #line 13 "..\..\Views\ErrorLog\Rss.cshtml"
                                  Write(errorLog.Type);

            
            #line default
            #line hidden
WriteLiteral(" occurred. ");


            
            #line 13 "..\..\Views\ErrorLog\Rss.cshtml"
                                                           Write(errorLog.Message);

            
            #line default
            #line hidden
WriteLiteral("</description>\r\n      <pubDate>");


            
            #line 14 "..\..\Views\ErrorLog\Rss.cshtml"
          Write(errorLog.Time.ToString("r"));

            
            #line default
            #line hidden
WriteLiteral("</pubDate>\r\n      <link>");


            
            #line 15 "..\..\Views\ErrorLog\Rss.cshtml"
       Write(url.Scheme);

            
            #line default
            #line hidden
WriteLiteral("://");


            
            #line 15 "..\..\Views\ErrorLog\Rss.cshtml"
                     Write(url.Authority);

            
            #line default
            #line hidden

            
            #line 15 "..\..\Views\ErrorLog\Rss.cshtml"
                                   Write(Url.Action("Default", "ErrorLog", new { id = errorLog.ID }));

            
            #line default
            #line hidden
WriteLiteral("</link>\r\n    </item>\r\n");


            
            #line 17 "..\..\Views\ErrorLog\Rss.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("  </channel>\r\n</rss>");


        }
    }
}
#pragma warning restore 1591
