#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Mvc.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Elfar;
    using Elfar.Mvc;
    using Elfar.Mvc.Properties;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Scripts.cshtml")]
    public partial class Scripts : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Scripts()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script type=\"application/json\">{\"Path\":\"");


            
            #line 1 "..\..\Views\ErrorLog\Scripts.cshtml"
                                    Write(Url.Content("~/elfar"));

            
            #line default
            #line hidden
WriteLiteral("\"}</script>\r\n<script src=\"");


            
            #line 2 "..\..\Views\ErrorLog\Scripts.cshtml"
        Write(Url.Content("~/elfar/script.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>");


        }
    }
}
#pragma warning restore 1591
