#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Mvc.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Elfar;
    using Elfar.Mvc;
    using Elfar.Mvc.Properties;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Title.cshtml")]
    public partial class Title : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Title()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div>Error Logging Filter and Route &nbsp;/&nbsp; <strong title=\"The name or id o" +
"f the web application\">");


            
            #line 1 "..\..\Views\ErrorLog\Title.cshtml"
                                                                                                   Write(ErrorLogProvider.Application);

            
            #line default
            #line hidden
WriteLiteral("</strong> &nbsp;/&nbsp; <strong title=\"The name of the server\">");


            
            #line 1 "..\..\Views\ErrorLog\Title.cshtml"
                                                                                                                                                                                               Write(Server.MachineName);

            
            #line default
            #line hidden
WriteLiteral("</strong></div>");


        }
    }
}
#pragma warning restore 1591
