#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.SignalR.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/SignalR.cshtml")]
    public class SignalR : System.Web.Mvc.WebViewPage<dynamic>
    {
        public SignalR()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"        <div id=""notify"" title=""New Error Log"">
            <p>
                <span>A new error has just been logged.</span>
                <span>Refresh the page to view the error log.</span>
            </p>
        </div>
        <script type=""text/javascript"" src=""");


            
            #line 7 "..\..\Views\ErrorLog\SignalR.cshtml"
                                       Write(Url.Action("JavaScript"));

            
            #line default
            #line hidden
WriteLiteral("?file=SignalR\"></script>\r\n        <script type=\"text/javascript\" src=\"");


            
            #line 8 "..\..\Views\ErrorLog\SignalR.cshtml"
                                       Write(Url.Content("~/signalr/hubs"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>");


        }
    }
}
#pragma warning restore 1591
