#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Mail.Views.Emails
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Emails/ErrorLog.cshtml")]
    public class ErrorLog : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ErrorLog()
        {
        }
        public override void Execute()
        {

WriteLiteral("From: ");


            
            #line 2 "..\..\Views\Emails\ErrorLog.cshtml"
 Write(Model.From);

            
            #line default
            #line hidden
WriteLiteral("\r\nTo: ");


            
            #line 3 "..\..\Views\Emails\ErrorLog.cshtml"
Write(Model.To);

            
            #line default
            #line hidden
WriteLiteral("\r\nSubject: ");


            
            #line 4 "..\..\Views\Emails\ErrorLog.cshtml"
    Write(Model.Subject);

            
            #line default
            #line hidden
WriteLiteral("\r\nViews: Text, Html");


        }
    }
}
#pragma warning restore 1591
