#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Mail.Views.Emails
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Emails/ErrorLog.Text.cshtml")]
    public partial class ErrorLog_Text : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ErrorLog_Text()
        {
        }
        public override void Execute()
        {

WriteLiteral("Content-Type: text/plain\r\n\r\n");


            
            #line 4 "..\..\Views\Emails\ErrorLog.Text.cshtml"
Write(Model.Subject);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 5 "..\..\Views\Emails\ErrorLog.Text.cshtml"
 if (Model.Time > DateTime.MinValue) {

            
            #line default
            #line hidden
WriteLiteral("Generated: ");


            
            #line 6 "..\..\Views\Emails\ErrorLog.Text.cshtml"
        Write(Model.Time.ToString("r"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 7 "..\..\Views\Emails\ErrorLog.Text.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("Source:\r\n");


            
            #line 9 "..\..\Views\Emails\ErrorLog.Text.cshtml"
Write(Model.Source);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\nStack Trace:\r\n");


            
            #line 12 "..\..\Views\Emails\ErrorLog.Text.cshtml"
Write(Model.StackTrace);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\nPowered by Error Logging Filter and Route (ELFAR) for ASP.NET MVC, Copyright " +
"(c) 2012, Steven Bey. All rights reserved.\r\nLicensed under Apache License, Versi" +
"on 2.0.");


        }
    }
}
#pragma warning restore 1591
