#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Default.cshtml")]
    public class Default : System.Web.Mvc.WebViewPage<Elfar.Models.Default>
    {
        public Default()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\ErrorLog\Default.cshtml"
  
    var errorLog = Model.ErrorLog;
    var id = errorLog.ID;
 

            
            #line default
            #line hidden
WriteLiteral(@"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"">
<html xmlns=""http://www.w3.org/1999/xhtml"">
	<head>
		<meta http-equiv=""X-UA-Compatible"" content=""IE=EmulateIE7"" />
		<title>Error: ");


            
            #line 10 "..\..\Views\ErrorLog\Default.cshtml"
           Write(errorLog.Type);

            
            #line default
            #line hidden
WriteLiteral(" [");


            
            #line 10 "..\..\Views\ErrorLog\Default.cshtml"
                           Write(id);

            
            #line default
            #line hidden
WriteLiteral("]</title>\r\n        <link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 11 "..\..\Views\ErrorLog\Default.cshtml"
                                                Write(Url.Action("Stylesheet"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\t</head>\r\n\t<body>\r\n\t\t<h1>");


            
            #line 14 "..\..\Views\ErrorLog\Default.cshtml"
 Write(errorLog.Message);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\t\t<ul id=\"navigation\">\r\n\t\t\t<li><a href=\"");


            
            #line 16 "..\..\Views\ErrorLog\Default.cshtml"
           Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"List of logged errors\">Errors</a></li>\r\n\t\t</ul>\r\n        <p id=\"title\"><" +
"span id=\"error-type\">");


            
            #line 18 "..\..\Views\ErrorLog\Default.cshtml"
                                       Write(errorLog.Type);

            
            #line default
            #line hidden
WriteLiteral("</span><span id=\"separator\">: </span><span id=\"error-message\">");


            
            #line 18 "..\..\Views\ErrorLog\Default.cshtml"
                                                                                                                   Write(errorLog.Message);

            
            #line default
            #line hidden

            
            #line 18 "..\..\Views\ErrorLog\Default.cshtml"
                                                                                                                                         WriteLiteral("</span></p>\r\n\t\t<pre id=\"stack-trace\">");

            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\ErrorLog\Default.cshtml"
                           Html.RenderPartial("StackTrace", Model.StackTrace); 
            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n");


            
            #line 20 "..\..\Views\ErrorLog\Default.cshtml"
           var date = errorLog.Time; 

            
            #line default
            #line hidden
WriteLiteral("\t\t<p>Logged on ");


            
            #line 21 "..\..\Views\ErrorLog\Default.cshtml"
          Write(date.ToLongDateString());

            
            #line default
            #line hidden
WriteLiteral(" at ");


            
            #line 21 "..\..\Views\ErrorLog\Default.cshtml"
                                      Write(date.ToShortTimeString());

            
            #line default
            #line hidden
WriteLiteral(" (Local)</p>\r\n\t\t<p>See also: (opens in new window)</p>\r\n\t\t<ul>\r\n");


            
            #line 24 "..\..\Views\ErrorLog\Default.cshtml"
         if(!string.IsNullOrWhiteSpace(errorLog.Html))
        {

            
            #line default
            #line hidden
WriteLiteral("            <li>The <a href=\"");


            
            #line 26 "..\..\Views\ErrorLog\Default.cshtml"
                        Write(Url.Action("Html", new { id }));

            
            #line default
            #line hidden
WriteLiteral("\" target=\"_blank\">original ASP.NET error page</a>.</li>\r\n");


            
            #line 27 "..\..\Views\ErrorLog\Default.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<li>Raw/Source data in <a href=\"");


            
            #line 28 "..\..\Views\ErrorLog\Default.cshtml"
                              Write(Url.Action("Xml", new { id }));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"alternate\" type=\"application/xml\" target=\"_blank\">XML</a> or\r\n            " +
"<a href=\"");


            
            #line 29 "..\..\Views\ErrorLog\Default.cshtml"
                Write(Url.Action("Json", new { id }));

            
            #line default
            #line hidden
WriteLiteral(@""" rel=""alternate"" type=""application/json"" target=""_blank"">JSON</a> format.</li>
		</ul>
        <div>
			<p class=""table-caption"">Server Variables</p>
			<div class=""scroll-view"">
				<table cellspacing=""0"">
                    <thead>
                        <tr>
                            <th style=""white-space: nowrap;"">Name</th>
                            <th style=""white-space: nowrap;"">Value</th>
                        </tr>
                    </thead>
                    <tbody>
");


            
            #line 42 "..\..\Views\ErrorLog\Default.cshtml"
                      
                        var variables = errorLog.ServerVariables;
                        var i = 0;
                     

            
            #line default
            #line hidden

            
            #line 46 "..\..\Views\ErrorLog\Default.cshtml"
                     foreach(var key in variables.Keys)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr class=\"");


            
            #line 48 "..\..\Views\ErrorLog\Default.cshtml"
                               Write(i++ % 2 == 0 ? "even" : "odd");

            
            #line default
            #line hidden
WriteLiteral("-row\">\r\n                            <td class=\"key-col\">");


            
            #line 49 "..\..\Views\ErrorLog\Default.cshtml"
                                           Write(key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");


            
            #line 50 "..\..\Views\ErrorLog\Default.cshtml"
                           Write(variables[key]);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        </tr>\r\n");


            
            #line 52 "..\..\Views\ErrorLog\Default.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n\t\t\t\t</table>\r\n\t\t\t</div>\r\n\t\t</div>\r\n");


            
            #line 57 "..\..\Views\ErrorLog\Default.cshtml"
   Html.RenderPartial("Footer"); 

            
            #line default
            #line hidden
WriteLiteral("\t</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
