#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Default.cshtml")]
    public class Default : System.Web.Mvc.WebViewPage<Elfar.Models.Default>
    {
        public Default()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\ErrorLog\Default.cshtml"
  
    var errorLog = Model.ErrorLog;
    var id = errorLog.ID;
 

            
            #line default
            #line hidden
WriteLiteral(@"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"">
<html xmlns=""http://www.w3.org/1999/xhtml"">
	<head>
		<meta http-equiv=""X-UA-Compatible"" content=""IE=EmulateIE7"" />
		<title>Error: ");


            
            #line 10 "..\..\Views\ErrorLog\Default.cshtml"
           Write(errorLog.Type);

            
            #line default
            #line hidden
WriteLiteral(" [");


            
            #line 10 "..\..\Views\ErrorLog\Default.cshtml"
                           Write(id);

            
            #line default
            #line hidden
WriteLiteral("]</title>\r\n        <link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 11 "..\..\Views\ErrorLog\Default.cshtml"
                                                Write(Url.Action("Stylesheet"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\t</head>\r\n\t<body>\r\n\t\t<h1>");


            
            #line 14 "..\..\Views\ErrorLog\Default.cshtml"
 Write(errorLog.Message);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\t\t<ul id=\"navigation\">\r\n\t\t\t<li><a href=\"");


            
            #line 16 "..\..\Views\ErrorLog\Default.cshtml"
           Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"List of logged errors\">Errors</a></li>\r\n\t\t</ul>\r\n        <p id=\"title\"><" +
"span id=\"error-type\">");


            
            #line 18 "..\..\Views\ErrorLog\Default.cshtml"
                                       Write(errorLog.Type);

            
            #line default
            #line hidden
WriteLiteral("</span><span id=\"separator\">: </span><span id=\"error-message\">");


            
            #line 18 "..\..\Views\ErrorLog\Default.cshtml"
                                                                                                                   Write(errorLog.Message);

            
            #line default
            #line hidden

            
            #line 18 "..\..\Views\ErrorLog\Default.cshtml"
                                                                                                                                         WriteLiteral("</span></p>\r\n\t\t<pre id=\"stack-trace\">");

            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\ErrorLog\Default.cshtml"
                           Html.RenderPartial("StackTrace", Model.StackTrace); 
            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n");


            
            #line 20 "..\..\Views\ErrorLog\Default.cshtml"
           var date = errorLog.Time; 

            
            #line default
            #line hidden
WriteLiteral("\t\t<p>Logged on ");


            
            #line 21 "..\..\Views\ErrorLog\Default.cshtml"
          Write(date.ToLongDateString());

            
            #line default
            #line hidden
WriteLiteral(" at ");


            
            #line 21 "..\..\Views\ErrorLog\Default.cshtml"
                                      Write(date.ToShortTimeString());

            
            #line default
            #line hidden
WriteLiteral(" (Local)</p>\r\n\t\t<p>See also: (opens in new window)</p>\r\n        <ul>\r\n");


            
            #line 24 "..\..\Views\ErrorLog\Default.cshtml"
             if(!string.IsNullOrWhiteSpace(errorLog.Html))
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    The <a id=\"show-html\" href=\"#\">original" +
" ASP.NET error page</a>.\r\n                    <div id=\"dialog\" title=\"Original A" +
"SP.NET error page\">\r\n                        <iframe src=\"");


            
            #line 29 "..\..\Views\ErrorLog\Default.cshtml"
                                Write(Url.Action("Html", new { id }));

            
            #line default
            #line hidden
WriteLiteral("\" frameborder=\"0\" width=\"100%\" height=\"100%\"></iframe>\r\n                    </div" +
">\r\n                </li>\r\n");


            
            #line 32 "..\..\Views\ErrorLog\Default.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li>Raw/Source data in <a href=\"");


            
            #line 33 "..\..\Views\ErrorLog\Default.cshtml"
                                       Write(Url.Action("Xml", new { id }));

            
            #line default
            #line hidden
WriteLiteral("?download=true\" rel=\"alternate\" type=\"application/xml\">XML</a> or\r\n              " +
"  <a href=\"");


            
            #line 34 "..\..\Views\ErrorLog\Default.cshtml"
                    Write(Url.Action("Json", new { id }));

            
            #line default
            #line hidden
WriteLiteral(@"?download=true"" rel=""alternate"" type=""application/json"">JSON</a> format.</li>
        </ul>
        <div id=""tabs"">
            <ul>
                <li><a href=""#server-variables"">Server Variables</a></li>
                <li><a href=""#form"">Form</a></li>
                <li><a href=""#querystring"">QueryString</a></li>
                <li><a href=""#cookies"">Cookies</a></li>
            </ul>
            <div id=""server-variables"">
");


            
            #line 44 "..\..\Views\ErrorLog\Default.cshtml"
Write(Html.DisplayFor(m => m.ErrorLog.ServerVariables));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div id=\"form\">\r\n");


            
            #line 47 "..\..\Views\ErrorLog\Default.cshtml"
Write(Html.DisplayFor(m => m.ErrorLog.Form));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div id=\"querystring\">\r\n");


            
            #line 50 "..\..\Views\ErrorLog\Default.cshtml"
Write(Html.DisplayFor(m => m.ErrorLog.QueryString));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div id=\"cookies\">\r\n");


            
            #line 53 "..\..\Views\ErrorLog\Default.cshtml"
Write(Html.DisplayFor(m => m.ErrorLog.Cookies));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");


            
            #line 56 "..\..\Views\ErrorLog\Default.cshtml"
   Html.RenderPartial("Footer"); 

            
            #line default
            #line hidden
WriteLiteral("        <script type=\"text/javascript\" src=\"");


            
            #line 57 "..\..\Views\ErrorLog\Default.cshtml"
                                       Write(Url.Action("JavaScript"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n        <script type=\"text/javascript\" src=\"");


            
            #line 58 "..\..\Views\ErrorLog\Default.cshtml"
                                       Write(Url.Action("JavaScript"));

            
            #line default
            #line hidden
WriteLiteral("?file=Default\"></script>\r\n\t</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
