#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Footer.cshtml")]
    public class Footer : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Footer()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"		<p id=""Footer"">
            Powered by Error Logging Filter and Route (ELFAR) for ASP.NET MVC, Copyright &#169; 2012, Steven Bey. All rights reserved.
            Licensed under <a href=""http://www.apache.org/licenses/LICENSE-2.0"">Apache License, Version 2.0</a>.
        </p>");


        }
    }
}
#pragma warning restore 1591
