#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Views\ErrorLog\Index.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\ErrorLog\Index.cshtml"
    using Elfar;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<Elfar.Models.Index>
    {
        public Index()
        {
        }
        public override void Execute()
        {



WriteLiteral(@"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"">
<html xmlns=""http://www.w3.org/1999/xhtml"">
    <head>
        <meta http-equiv=""X-UA-Compatible"" content=""IE=EmulateIE7"" />
        <title>Error log for ");


            
            #line 8 "..\..\Views\ErrorLog\Index.cshtml"
                        Write(Model.Application);

            
            #line default
            #line hidden
WriteLiteral(" on ");


            
            #line 8 "..\..\Views\ErrorLog\Index.cshtml"
                                              Write(Server.MachineName);

            
            #line default
            #line hidden
WriteLiteral(" (Page #");


            
            #line 8 "..\..\Views\ErrorLog\Index.cshtml"
                                                                         Write(Model.Number);

            
            #line default
            #line hidden
WriteLiteral(")</title>\r\n        <link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 9 "..\..\Views\ErrorLog\Index.cshtml"
                                                Write(Url.Action("Stylesheet"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        <link rel=\"alternate\" type=\"application/rss+xml\" title=\"RSS\" href=\"" +
"");


            
            #line 10 "..\..\Views\ErrorLog\Index.cshtml"
                                                                      Write(Url.Action("Rss"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        <meta http-equiv=\"refresh\" content=\"60\" />\r\n    </head>\r\n    <body>" +
"\r\n        <h1>Error Log for <span>");


            
            #line 14 "..\..\Views\ErrorLog\Index.cshtml"
                           Write(Model.Application);

            
            #line default
            #line hidden
WriteLiteral(" on ");


            
            #line 14 "..\..\Views\ErrorLog\Index.cshtml"
                                                 Write(Server.MachineName);

            
            #line default
            #line hidden
WriteLiteral("</span></h1>\r\n");


            
            #line 15 "..\..\Views\ErrorLog\Index.cshtml"
         if(Model.Total != 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <ul id=\"navigation\">\r\n                <li><a href=\"");


            
            #line 18 "..\..\Views\ErrorLog\Index.cshtml"
                        Write(Url.Action("Rss"));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"RSS feed of recent errors\">RSS Feed</a></li>\r\n                <li><a hre" +
"f=\"");


            
            #line 19 "..\..\Views\ErrorLog\Index.cshtml"
                        Write(Url.Action("Digest"));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"RSS feed of errors within recent days\">RSS Digest</a></li>\r\n            " +
"    <li><a href=\"");


            
            #line 20 "..\..\Views\ErrorLog\Index.cshtml"
                        Write(Url.Action("Download"));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Download the entire log as CSV\">Download</a></li>\r\n            </ul>\r\n");



WriteLiteral(@"            <p id=""sizes"">
                Show
                <a href=""?page=1&amp;size=10"" rel=""start"">10</a>,
                <a href=""?page=1&amp;size=15"" rel=""start"">15</a>,
                <a href=""?page=1&amp;size=20"" rel=""start"">20</a>,
                <a href=""?page=1&amp;size=25"" rel=""start"">25</a>,
                <a href=""?page=1&amp;size=30"" rel=""start"">30</a>,
                <a href=""?page=1&amp;size=50"" rel=""start"">50</a> or
                <a href=""?page=1&amp;size=100"" rel=""start"">100</a>
                errors per page.
            </p>
");


            
            #line 33 "..\..\Views\ErrorLog\Index.cshtml"
            Html.RenderPartial("Pagination");

            
            #line default
            #line hidden
WriteLiteral(@"            <table cellspacing=""0"">
                <thead>
                    <tr>
                        <th title=""Number"">#</th>
                        <th>Host</th>
                        <th>Application</th>
                        <th>Code</th>
                        <th>Type</th>
                        <th>Error</th>
                        <th>User</th>
                        <th>Date</th>
                        <th>Time (Local)</th>
                    </tr>
                </thead>
                <tbody>
");


            
            #line 49 "..\..\Views\ErrorLog\Index.cshtml"
                       var i = 0; 

            
            #line default
            #line hidden

            
            #line 50 "..\..\Views\ErrorLog\Index.cshtml"
                     foreach(var errorLog in Model.Errors)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr class=\"");


            
            #line 52 "..\..\Views\ErrorLog\Index.cshtml"
                               Write((i % 2) == 0 ? "even" : "odd");

            
            #line default
            #line hidden
WriteLiteral("-row\">\r\n                            <td>");


            
            #line 53 "..\..\Views\ErrorLog\Index.cshtml"
                            Write(Model.From + i++);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");


            
            #line 54 "..\..\Views\ErrorLog\Index.cshtml"
                           Write(errorLog.Host);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");


            
            #line 55 "..\..\Views\ErrorLog\Index.cshtml"
                           Write(errorLog.Application);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td class=\"code-col\"><span title=\"");


            
            #line 56 "..\..\Views\ErrorLog\Index.cshtml"
                                                         Write(HttpWorkerRequest.GetStatusDescription(errorLog.Code.GetValueOrDefault()));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 56 "..\..\Views\ErrorLog\Index.cshtml"
                                                                                                                                     Write(errorLog.Code);

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n                            <td class=\"type-col\"><span title=\"");


            
            #line 57 "..\..\Views\ErrorLog\Index.cshtml"
                                                         Write(errorLog.Type);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 57 "..\..\Views\ErrorLog\Index.cshtml"
                                                                         Write(errorLog.Type.ShortName());

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n                            <td><span>");


            
            #line 58 "..\..\Views\ErrorLog\Index.cshtml"
                                 Write(errorLog.Message);

            
            #line default
            #line hidden
WriteLiteral("</span> ");


            
            #line 58 "..\..\Views\ErrorLog\Index.cshtml"
                                                          Write(Html.ActionLink("Details…", "Default", "ErrorLog", new { id = errorLog.ID }, null));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");


            
            #line 59 "..\..\Views\ErrorLog\Index.cshtml"
                           Write(errorLog.User);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td class=\"date-col\"><span title=\"");


            
            #line 60 "..\..\Views\ErrorLog\Index.cshtml"
                                                         Write(errorLog.Time.ToLongDateString());

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 60 "..\..\Views\ErrorLog\Index.cshtml"
                                                                                            Write(errorLog.Time.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n                            <td class=\"time-col\"><span title=\"");


            
            #line 61 "..\..\Views\ErrorLog\Index.cshtml"
                                                         Write(errorLog.Time.ToShortTimeString());

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 61 "..\..\Views\ErrorLog\Index.cshtml"
                                                                                             Write(errorLog.Time.ToShortTimeString());

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n                        </tr>\r\n");


            
            #line 63 "..\..\Views\ErrorLog\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n");


            
            #line 66 "..\..\Views\ErrorLog\Index.cshtml"
            Html.RenderPartial("Pagination");
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>No errors found.</p> \r\n");


            
            #line 71 "..\..\Views\ErrorLog\Index.cshtml"
        }

            
            #line default
            #line hidden

            
            #line 72 "..\..\Views\ErrorLog\Index.cshtml"
           Html.RenderPartial("Footer"); 

            
            #line default
            #line hidden
WriteLiteral("    </body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
