#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Pagination.cshtml")]
    public class Pagination : System.Web.Mvc.WebViewPage<Elfar.Models.Index>
    {
        public Pagination()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\ErrorLog\Pagination.cshtml"
  
    var pages = Model.Pages;
    var size = Model.Size == 15 ? "" : "&size=" + Model.Size;


            
            #line default
            #line hidden
WriteLiteral("        <p>\r\n");


            
            #line 7 "..\..\Views\ErrorLog\Pagination.cshtml"
             if(Model.Number > 2) {
            
            #line default
            #line hidden
WriteLiteral(" <a href=\"");


            
            #line 7 "..\..\Views\ErrorLog\Pagination.cshtml"
                                        Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("?page=1");


            
            #line 7 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                    Write(size);

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"first\" title=\"First page (#1)\">[&lt;&lt;]</a> ");


            
            #line 7 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                                                                                    }
            else {
            
            #line default
            #line hidden
WriteLiteral(" <a rel=\"first\">[&lt;&lt;]</a> ");


            
            #line 8 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                 }

            
            #line default
            #line hidden

            
            #line 9 "..\..\Views\ErrorLog\Pagination.cshtml"
             if(Model.Number > 1) {
            
            #line default
            #line hidden
WriteLiteral(" <a href=\"");


            
            #line 9 "..\..\Views\ErrorLog\Pagination.cshtml"
                                        Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("?page=");


            
            #line 9 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                  Write(Model.Previous);

            
            #line default
            #line hidden

            
            #line 9 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                                 Write(size);

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"previous\" title=\"Previous page (#");


            
            #line 9 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                                                                              Write(Model.Previous);

            
            #line default
            #line hidden
WriteLiteral(")\">[&lt;]</a> ");


            
            #line 9 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                                                                                                                }
            else {
            
            #line default
            #line hidden
WriteLiteral(" <a rel=\"previous\">[&lt;]</a> ");


            
            #line 10 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("            Errors ");


            
            #line 11 "..\..\Views\ErrorLog\Pagination.cshtml"
              Write(Model.From);

            
            #line default
            #line hidden
WriteLiteral(" to ");


            
            #line 11 "..\..\Views\ErrorLog\Pagination.cshtml"
                             Write(Model.To);

            
            #line default
            #line hidden
WriteLiteral(" of ");


            
            #line 11 "..\..\Views\ErrorLog\Pagination.cshtml"
                                          Write(Model.Total);

            
            #line default
            #line hidden
WriteLiteral(" (page ");


            
            #line 11 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                             Write(Model.Number);

            
            #line default
            #line hidden
WriteLiteral(" of ");


            
            #line 11 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                              Write(pages);

            
            #line default
            #line hidden
WriteLiteral(")\r\n");


            
            #line 12 "..\..\Views\ErrorLog\Pagination.cshtml"
             if(Model.Number < pages) {
            
            #line default
            #line hidden
WriteLiteral(" <a href=\"");


            
            #line 12 "..\..\Views\ErrorLog\Pagination.cshtml"
                                            Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("?page=");


            
            #line 12 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                      Write(Model.Next);

            
            #line default
            #line hidden

            
            #line 12 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                                 Write(size);

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"next\" title=\"Next page (#");


            
            #line 12 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                                                                      Write(Model.Next);

            
            #line default
            #line hidden
WriteLiteral(")\">[&gt;]</a> ");


            
            #line 12 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                                                                                                    }
            else {
            
            #line default
            #line hidden
WriteLiteral(" <a rel=\"next\">[&gt;]</a> ");


            
            #line 13 "..\..\Views\ErrorLog\Pagination.cshtml"
                                            }

            
            #line default
            #line hidden

            
            #line 14 "..\..\Views\ErrorLog\Pagination.cshtml"
             if(Model.Number < pages - 1) {
            
            #line default
            #line hidden
WriteLiteral(" <a href=\"");


            
            #line 14 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("?page=");


            
            #line 14 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                          Write(pages);

            
            #line default
            #line hidden

            
            #line 14 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                                Write(size);

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"last\" title=\"Last page (#");


            
            #line 14 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                                                                     Write(Model.Pages);

            
            #line default
            #line hidden
WriteLiteral(")\">[&gt;&gt;]</a> ");


            
            #line 14 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                                                                                                                        }
            else {
            
            #line default
            #line hidden
WriteLiteral(" <a rel=\"last\">[&gt;&gt;]</a> ");


            
            #line 15 "..\..\Views\ErrorLog\Pagination.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("        </p>\r\n");


        }
    }
}
#pragma warning restore 1591
