#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Elfar;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Stylesheets.cshtml")]
    public class Stylesheets : System.Web.Mvc.WebViewPage<IErrorLogPlugin[]>
    {
        public Stylesheets()
        {
        }
        public override void Execute()
        {

WriteLiteral("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 2 "..\..\Views\ErrorLog\Stylesheets.cshtml"
                                                Write(Url.Action("Stylesheet"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");


            
            #line 3 "..\..\Views\ErrorLog\Stylesheets.cshtml"
     foreach(var plugin in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 5 "..\..\Views\ErrorLog\Stylesheets.cshtml"
                                                Write(Url.Action("Stylesheet"));

            
            #line default
            #line hidden
WriteLiteral("?file=");


            
            #line 5 "..\..\Views\ErrorLog\Stylesheets.cshtml"
                                                                               Write(plugin.Name());

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");


            
            #line 6 "..\..\Views\ErrorLog\Stylesheets.cshtml"
    }
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
