#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Views.ErrorLog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/Stylesheet.cshtml")]
    public class Stylesheet : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Stylesheet()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\ErrorLog\Stylesheet.cshtml"
   Response.ContentType = "text/css"; 

            
            #line default
            #line hidden
WriteLiteral("/*\r\n   ELFAR - Error Logging Filter and Route for ASP.NET MVC\r\n   Copyright (c) 2" +
"004-9 Atif Aziz. All rights reserved.\r\n  \r\n    Author(s):\r\n  \r\n        Atif Aziz" +
", http://www.raboof.com\r\n        Steven Bey\r\n  \r\n   Licensed under the Apache Li" +
"cense, Version 2.0 (the \"License\");\r\n   you may not use this file except in comp" +
"liance with the License.\r\n   You may obtain a copy of the License at\r\n  \r\n      " +
"http://www.apache.org/licenses/LICENSE-2.0\r\n  \r\n   Unless required by applicable" +
" law or agreed to in writing, software\r\n   distributed under the License is dist" +
"ributed on an \"AS IS\" BASIS,\r\n   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, e" +
"ither express or implied.\r\n   See the License for the specific language governin" +
"g permissions and\r\n   limitations under the License.\r\n*/\r\n\r\na { color: #CCCCCC; " +
"text-decoration: none; }\r\na[href] { color: #0033CC; }\r\na[href]:visited { color: " +
"Navy; }\r\na[href]:hover { color: #FF6600; }\r\n\r\nbody { font-family: Verdana; font-" +
"size: 70%; background-color: #fff; }\r\n\r\nh1 { font-family: Verdana; font-weight: " +
"normal; color: #0A6CCE; font-size: 175%; }\r\n\r\nimg { border: none; }\r\n\r\npre, code" +
" { font-family: \"Courier New\" ,Courier; }\r\n\r\ntable { width: 100%; border-collaps" +
"e: collapse; }\r\ntd { border: solid 1px silver; padding: 0.4em; vertical-align: t" +
"op; }\r\nth { text-align: left; background-color: #0A6CCE; padding: 0.4em; color: " +
"White; vertical-align: top; border: solid 1px silver; }\r\n\r\n#error-type,\r\n#error-" +
"message { display: block; }\r\n\r\n#navigation { margin: 0; list-style-type: none; t" +
"ext-transform: uppercase; font-size: 80%; padding: 0.25em 0; color: #fff; backgr" +
"ound-color: #aaa; border-top: solid 1px #aaa; border-bottom: solid 1px #aaa; }\r\n" +
"#navigation a { text-decoration: none; padding: 0.25em 1em; border: solid 1px #a" +
"aa; border-right: solid 1px #fff; color: #fff; }\r\n#navigation a:hover { backgrou" +
"nd-color: #fff; color: #444; border: solid 1px #aaa; }\r\n#navigation li { display" +
": inline; }\r\n\r\n#separator { display: none; }\r\n\r\n#sizes { float: right; }\r\n\r\n#sta" +
"ck-trace { font-size: 110%; background-color: #ffffcc; padding: 1em; width: 97.9" +
"%; }\r\n#stack-trace .type { color: #00008B; }\r\n#stack-trace .name { color: #666; " +
"}\r\n#stack-trace .method { color: #008B8B; font-weight: bolder; }\r\n#stack-trace ." +
"file,\r\n#stack-trace .line { color: #8B008B; }\r\n\r\n#title { font-weight: bold; fon" +
"t-size: 120%; }\r\n\r\n.code-col,\r\n.date-col,\r\n.time-col { text-align: right; }\r\n\r\n." +
"key-col,\r\n.type-col { font-weight: bold; }\r\n\r\n.odd-row { background-color: #e9e9" +
"e9; }\r\n\r\n.table-caption { background-color: navy; margin: 0; color: white; paddi" +
"ng: 0.4em; font-weight: bold; }\r\n\r\n");


WriteLiteral("@media screen {\r\n    #stack-trace { overflow: scroll; }\r\n    .scroll-view { width" +
": 100%; overflow: scroll; }\r\n}\r\n");


WriteLiteral("@media print {\r\n    #navigation { display: none; }\r\n}");


        }
    }
}
#pragma warning restore 1591
