#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elfar.Mvc.Views.ErrorLog.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Elfar;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorLog/DisplayTemplates/StackTrace.cshtml")]
    public class StackTrace : System.Web.Mvc.WebViewPage<Elfar.Mvc.Models.StackTrace>
    {
        public StackTrace()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\ErrorLog\DisplayTemplates\StackTrace.cshtml"
Write(Html.Raw(Model.ToString()));

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
